### ISSUE TITLE
Criação de ordem com Receiver

### ISSUE THREAD

**Issue by mayroncachina** [robertons/py3wirecard#1]
Olá, não consegui realizar a criação de uma ordem adicionando um Receiver. Isso está implementado, se sim, poderia colocar na documentação o exemplo?

Em PHP seria algo assim:

```
    $order = $moip->orders()->setOwnId($id)
    ->addItem($descricao,1, "", intval(str_replace('.','',$valor)))
    ->setCustomerId($customer)
    ->addReceiver($receiver, "SECONDARY", intval($valor_organizador), 0, false)
    ->create();
```

Obrigado.

**Comment by robertons** [comment]
Olá, esta implementado sim:

Exemplo: 

```
recebedor = Receiver()
recebedor.type = 'SECONDARY' 
recebedor.feePayor = False
recebedor.moipAccount = MoipAccount(id='ID CONTA', login='LOGIN CONTA', fullname='NOME CONTA')
recebedor.amount = Amount(percentual=10) 

compra = Order()
compra.ownId = "1234"
.
.
compra.receivers.append(recebedor)
compra.create()
```

 O amount pode ser valor fixo ou percentual, no exemplo abaixo esta tudo inline e com amount fixo:

```
compra = Order()
compra.ownId = "1234"
.
.
compra.receivers.append(Receiver(type = 'SECONDARY', feePayor = False, moipAccount = MoipAccount(id='ID CONTA', login='LOGIN CONTA', fullname='NOME CONTA'), amount = Amount(fixed = 10000)))
compra.create()
```

> **feePayor:**  Flag para definir se o recebedor é o pagador da taxa Wirecard, valores possíveis: True, False.
> **type:** Define qual o tipo de recebedor do pagamento, valores possíveis: PRIMARY, SECONDARY
> **Amount:** Valor fixo ou percentual  a ser recebido

Testa no Sandbox, vou deixar o Issue aberto caso precise fazer alguma modificação. 

Abraço.

**Comment by mayroncachina** [comment]
Massa, testado e funcionando!
Só frisar 2 coisas que achei
```

            compra.receivers.append(Receiver(type='SECONDARY', feePayor=False,
                                             moipAccount=MoipAccount(id='MPA-5C0F99A2CB51'),
                                             amount=Amount(percentual=str(compra.evento.taxa_negociacao))))
```

1) percentual em Amount, deve ser String.
2) MoipAccount, só precisa do id

Mas parabéns! fazia tempo que procurava essa implementação em python, tinha uma em php, mas como migrei foi uma mão na roda...

**Comment by robertons** [comment]
Mayron,

Eu não tive a oportunidade de testar todas as funções do E-Commerce da Wirecard, a divisão com receivers por exemplo eu nao tinha testado apenas implementado baseado na documentação por isso pedi para voce testar. rs 

Realmente fui conferir os campos amount.fixed e o amount.percentual  na entity e estão como string fiquei na dúvida e fui conferir a documentação e realmente são, para facilitar a vida do programador eu vou colocar no decorador String() a conversão.

**Comment by robertons** [comment]
Disponibilizei versão  0.0.4 com a conversão string automática, vai poupar a necessidade de fazer o cast str(...) em campos string.

Só mandar um pip upgrade ai:

```sh
pip3 install --upgrade py3wirecard 
```

Abraços
